version: '3.7'
services:
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx

  python:
    restart: always
    build: ./docker/python/
    volumes:
      - ./src:/home/src
      - ./logs:/logs
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    expose:
      - "3031"
    depends_on:
      - db
    working_dir: /home/src
    command: bash -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:3031"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    user: "${UID}:${GID}"

  nginx:
    restart: always
    image: nginx
    depends_on:
      - python
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./static:/opt/apps/static/"


  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     - nginx
  #   restart: always
  #   environment:
  #     DOMAINS: 'ascreit.com -> http://nginx'
  #     # STAGE: 'local'
  #     STAGE: 'production'
  #     # FORCE_RENEW: 'true'
  #   volumes:
  #     - /data/ssl_certs:/var/lib/https-portal

  redis:
    image: redis:5.0.3-alpine
    tty: true
    container_name: redis
    expose:
      - "6379"


  worker:
    restart: always
    build: ./docker/python/
    volumes:
      - ./src:/home/src
      - ./logs:/logs
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    depends_on:
      - python
    working_dir: /home/src
    command: celery -A config worker --loglevel=info  --logfile=/logs/celery/worker.log --pidfile=
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    user: "${UID}:${GID}"


  monitor:
    restart: always
    build: ./docker/python/
    volumes:
      - ./src:/home/src
      - ./logs:/logs
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    depends_on:
      - worker
    working_dir: /home/src
    command: flower -A config --port=5555 --broker=redis://redis:6379
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    user: "${UID}:${GID}"
    ports:
      - "5555:5555"

volumes:
  db-store:
