# Generated by Django 3.0.5 on 2020-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmeaning',
            name='english_word',
        ),
        migrations.AddField(
            model_name='englishword',
            name='audio_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='englishword',
            name='mean',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='WordAudio',
        ),
        migrations.DeleteModel(
            name='WordMeaning',
        ),
    ]
