# Generated by Django 3.0.5 on 2020-04-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn_word', '0002_auto_20200423_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='last_displayed_at',
        ),
        migrations.CreateModel(
            name='WordSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_count', models.IntegerField(default=0)),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_summary', to='learn_word.EnglishWord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'word_summary',
            },
        ),
    ]
