# Generated by Django 3.0.5 on 2020-04-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0003_auto_20200423_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='wordsummary',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
