# Generated by Django 3.0.5 on 2020-04-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0004_auto_20200424_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='wordcategory',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='learn_word.WordCategory'),
        ),
    ]
