# Generated by Django 3.0.5 on 2020-04-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0005_auto_20200424_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlearnsetting',
            name='display_num',
        ),
        migrations.AddField(
            model_name='wordlearnsetting',
            name='learn_num',
            field=models.IntegerField(default=100),
        ),
    ]
