# Generated by Django 3.0.5 on 2020-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0007_wordsummary_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishword',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
