# Generated by Django 3.0.5 on 2020-05-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0008_englishword_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcategory',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
