# Generated by Django 3.0.5 on 2020-05-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0009_wordcategory_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('english_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_synonyms', to='learn_word.EnglishWord')),
                ('synonym_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='learn_word.EnglishWord')),
            ],
            options={
                'db_table': 'synonym',
            },
        ),
    ]
