# Generated by Django 3.0.5 on 2020-05-07 00:39

from django.db import migrations, models
import django.db.models.deletion


def initialize(apps, schema_editor):
    EnglishWord = apps.get_model('learn_word', 'EnglishWord')
    CategoryWordRelation = apps.get_model('learn_word', 'CategoryWordRelation')

    for word_obj in EnglishWord.objects.all():
        category = word_obj.category
        relation = CategoryWordRelation(
            english_word_id=word_obj.id,
            category_id=category.id,
        )
        relation.save()

def reverse_function(apps, schema_editor):
    EnglishWord = apps.get_model('learn_word', 'EnglishWord')
    CategoryWordRelation = apps.get_model('learn_word', 'CategoryWordRelation')

    for word_obj in EnglishWord.objects.all():
        rel = CategoryWordRelation.objects.filter(english_word_id=word_obj.id).first()
        if not rel:
            continue
        word_obj.category = rel.category
        word_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0010_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishword',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_words', to='learn_word.WordCategory'),
        ),
        migrations.CreateModel(
            name='CategoryWordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_word.WordCategory')),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_word.EnglishWord')),
            ],
            options={
                'db_table': 'category_word_relation',
            },
        ),
        migrations.AddField(
            model_name='wordcategory',
            name='words',
            field=models.ManyToManyField(through='learn_word.CategoryWordRelation', to='learn_word.EnglishWord'),
        ),
        migrations.RunPython(initialize, reverse_code=reverse_function),
        migrations.RemoveField(
            model_name='englishword',
            name='category',
        ),
    ]
