# Generated by Django 3.0.5 on 2020-05-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0011_auto_20200507_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Define',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning_en', models.CharField(max_length=255, null=True)),
                ('meaning_jp', models.CharField(max_length=255, null=True)),
                ('word_class', models.CharField(max_length=255)),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defines', to='learn_word.EnglishWord')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='define_children', to='learn_word.Define')),
            ],
            options={
                'db_table': 'define',
            },
        ),
        migrations.CreateModel(
            name='MeaningSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('define', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='define_synonyms', to='learn_word.Define')),
                ('english_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_define_synonyms', to='learn_word.EnglishWord')),
            ],
            options={
                'db_table': 'define_synonym',
            },
        ),
    ]
