# Generated by Django 3.0.5 on 2020-05-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0012_define_meaningsynonym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='define',
            old_name='meaning_jp',
            new_name='meaning_ja',
        ),
    ]
