# Generated by Django 3.0.5 on 2020-05-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0013_auto_20200509_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='define',
            name='word_class',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
