# Generated by Django 3.0.5 on 2020-05-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_word', '0016_auto_20200512_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='define',
            name='meaning_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='define',
            name='meaning_ja',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='englishword',
            name='mean',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Synonyms',
        ),
    ]
